sudo: required
services:
  - docker

before_install:
  - docker build -t abtayshete06/docker-react .

script:
  - docker run -e CI=true  abtayshete06/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-870022753381"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: "AKIA4VELFVRS66R3NTGY"
  secret_access_key: "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"
 
