sudo: required
services:
  - docker

before_install:
  - docker build -t abtayshete06/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  abtayshete06/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "my-react-app"
  env: "MyReactApp-env"
  bucket_name: elasticbeanstalk-ap-south-1-870022753381
  bucket_path: "my-react-app"
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key:
    secure: "$AWS_Secret_Access_Key"
 
